version: "3"
services:
  go:
    container_name: HackU2022_Spring_GO
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file:
      - ./docker/go/.env
    volumes:
      - ./go:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - "mysql"

  mysql:
    container_name: HackU2022_Spring_DB
    build:
      context: ./Docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./Docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
