### 本番ではGETメソッドのパラメータ「roomId」にはカンマ区切りで複数の部屋IDが入ります。
### REST CLIENTではカンマで区切るとリクエストが送れなくなるので複数の部屋IDを送って動作を調べたい時は、curl コマンドを打って確かめてください

### 部屋idから部屋の詳細情報を取得
GET  http://localhost:8080/api/room?roomId=1,2 HTTP/1.1

### 参加している部屋の一覧を取得（閲覧したことのある部屋一覧を見るときに叩く）
GET  http://localhost:8080/api/room/2/ HTTP/1.1

###部屋を建てるまたは、小部屋を作成する（childrenに部屋IDを追加していく）
POST  http://localhost:8080/api/room/ HTTP/1.1
Content-Type: application/json

{
    "roomName": "成人式2次会",
    "summary" : "gaburitikin",
    "roomMaker": "たなか"
}

### 参加者の追加
POST  http://localhost:8080/api/room/2/member/ HTTP/1.1
Content-Type: application/json

### 部屋の概要を変更
PUT  http://localhost:8080/api/room/1/ HTTP/1.1
content-type: application/json

{
    "summay": "名古屋駅周辺の居酒屋" // 変更後の部屋のデータ 変更点のみ送る
}

### 参加者の部屋の移動（名前、または備考欄を変更する時）
PUT  http://localhost:8080/api/room/1/member/2/ HTTP/1.1
content-type: application/json

{
    "comment": "こんにちは", // string? 変更後のコメント
}

### 部屋を削除
DELETE  http://localhost:8080/api/room/1/ HTTP/1.1

### 部屋からの退室
DELETE  http://localhost:8080/api/room/1/member/2/ HTTP/1.1